"""
digest_approach2.py
--------------------
Part 4, Approach 2 - Structured Generation + Verification.

Flow: Metrics -> LLM -> Structured JSON claims -> Programmatic
Verification (verifier.py) -> Final digest (assembled by OUR code, only
from claims that passed verification).

The key difference from Approach 1: the LLM never gets to freely write
the final prose in one shot. It first must output a list of discrete,
checkable claims in a fixed JSON shape. Every claim is verified before
any of it is allowed into the digest that gets shown to a human. Claims
that fail verification are dropped and flagged rather than shown.
"""

import json
import re
from llm_client import call_llm
from verifier import verify_claims

SYSTEM_PROMPT = (
    "You are a retail data analyst. You will be given calculated weekly "
    "metrics for one store. Output ONLY a JSON array of claim objects - no "
    "prose, no markdown formatting, no explanation. Each object must have "
    "exactly these fields: store_id (string), week (integer), metric (one "
    "of: weekly_revenue, weekly_transaction_count, weekly_return_rate, "
    "weekly_staffing_hours, sales_per_staffed_hour, online_sales_share_pct, "
    "revenue_per_sqft), claim_type ('absolute' or 'change_percent'), value "
    "(number), and a short human-readable 'text' field describing the claim "
    "in one sentence. Produce 4-6 claims covering the most notable aspects "
    "of the data (biggest changes, anything missing, anything unusual)."
)


def _extract_json_array(text: str):
    """
    Defensively extract a JSON array from an LLM response. Handles:
    - markdown code fences (```json ... ```)
    - extra prose/explanation before or after the array
    - Gemini occasionally prepending/appending stray text even when told not to
    """
    text = text.strip()
    text = re.sub(r"^```(json)?", "", text).strip()
    text = re.sub(r"```$", "", text).strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Fallback: grab the substring between the first '[' and the last ']'
    start = text.find("[")
    end = text.rfind("]")
    if start != -1 and end != -1 and end > start:
        candidate = text[start:end + 1]
        try:
            return json.loads(candidate)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"Could not parse JSON claims from model output even after cleanup. "
                f"Raw response was:\n{text[:1000]}"
            ) from e

    raise ValueError(f"No JSON array found in model output. Raw response was:\n{text[:1000]}")


def generate_claims_approach2(metrics_df, store_id: str, week: int):
    row = metrics_df[(metrics_df["store_id"] == store_id) & (metrics_df["week"] == week)]
    if row.empty:
        raise ValueError(f"No data for {store_id} / week {week}")
    current = row.iloc[0].to_dict()

    prev_row = metrics_df[(metrics_df["store_id"] == store_id) & (metrics_df["week"] == week - 1)]
    previous = prev_row.iloc[0].to_dict() if not prev_row.empty else None

    metrics_summary = json.dumps(
        {"current_week": {k: (None if v != v else v) for k, v in current.items()},
         "previous_week": ({k: (None if v != v else v) for k, v in previous.items()} if previous else None)},
        default=str, indent=2,
    )

    prompt = f"Calculated metrics:\n{metrics_summary}\n\nOutput the JSON array of claims now."
    # json_mode=True forces the API to only return valid JSON - fixes the
    # truncation/malformed-JSON issues seen when relying on prompt instructions alone.
    raw = call_llm(prompt, system=SYSTEM_PROMPT, max_tokens=2000, json_mode=True)
    claims = _extract_json_array(raw)
    return claims, current, previous


def build_verified_digest(claims, metrics_df, store_id, week):
    """
    Runs every claim through the verifier, keeps only PASS claims,
    and assembles the final digest text OURSELVES (not the LLM) from
    the verified claims - this is the key structural guarantee of
    Approach 2.
    """
    results = verify_claims(claims, metrics_df)
    passed = [r for r in results if r["status"] == "PASS"]
    failed = [r for r in results if r["status"] == "FAIL"]

    lines = [f"**Weekly Operations Digest — {store_id}, Week {week}**\n"]
    for r in passed:
        lines.append(f"- {r['claim'].get('text', r['claim'])}")

    if failed:
        lines.append(f"\n[{len(failed)} claim(s) generated by the model were rejected "
                      f"by verification and excluded from this digest.]")

    return "\n".join(lines), results